services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Ppl\PplRightsManagement\:
    resource: '../Classes/*'

  Ppl\PplRightsManagement\Controller\:
    resource: '../Classes/Controller/*'
    public: true

  Ppl\PplRightsManagement\Configuration\AbstractRightsManagementModuleConfiguration: '@Ppl\PplRightsManagement\Configuration\RightsManagementModuleConfiguration'

  Ppl\PplRightsManagement\Configuration\RightsManagementModuleConfiguration:
    public: true

  Ppl\PplRightsManagement\EventListener\BackendGroupModuleAccessListener:
    tags:
      - name: event.listener
        identifier: 'ppl-rights-management/backend-group-module-access'
